name: stellar
recipe: wordpress
config:
  via: nginx
  webroot: www
  database: mariadb
  xdebug: true

services:

  # Install WordPress
  appserver:
    run:
      - /app/lando/wordpress-install.sh
    overrides:
      volumes:
        - ./plugins:/app/www/wp-content/plugins
        - ./themes:/app/www/wp-content/themes

  # Add PhpMyAdmin in pma.stellar.lndo.site
  pma:
    type: phpmyadmin

  # Add MailCatcher in mail.stellar.lndo.site
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  # Add a Cache database
  redis:
    type: redis
    portforward: false

proxy:

  # Enable Widlcards for multisite to work
  appserver_nginx:
    - "*.stellar.lndo.site"
    - stellar.lndo.site

  pma:
    - pma.stellar.lndo.site

  mailhog:
    - mail.stellar.lndo.site


tooling:

  # Change the wp command to account for the new webroot
  wp:
    service: appserver
    cmd: wp --path=/app/www
