name: stellarwp
recipe: wordpress
config:
  via: nginx
  webroot: wp-www
  database: mariadb
  xdebug: true

services:

  # Install WordPress
  appserver:
    run:
      - /app/lando/wordpress-install.sh
    overrides:
      volumes:
        # Must match `webroot` above
        - ./plugins:/app/wp-www/wp-content/plugins
        - ./themes:/app/wp-www/wp-content/themes

  # Add PhpMyAdmin in pma.stellarwp.lndo.site
  pma:
    ssl: true
    type: phpmyadmin

  # Add MailCatcher in mail.stellarwp.lndo.site
  mailhog:
    ssl: true
    type: mailhog
    hogfrom:
      - appserver

  # Add a Cache database
  redis:
    type: redis
    portforward: false

proxy:

  # Enable Widlcards for multisite to work
  appserver_nginx:
    - "*.stellarwp.lndo.site"
    - stellarwp.lndo.site

  pma:
    - stellarwp-pma.lndo.site

  mailhog:
    - stellarwp-mail.lndo.site

tooling:

  # Change the wp command to account for the new webroot
  wp:
    service: appserver
    cmd: wp
    dir: /var/wp-www
