version: "3"

services:

  # Generate SSL certs for the local development environment.
  mkcert:
    build: ./docker/mkcert
    container_name: stellar-dev-mkcert
    volumes:
      - cert-data:/root/.local/share/mkcert
    command: mkcert -cert-file "stellar-dev-webserver.crt" -key-file "stellar-dev-webserver.key" "stellar-dev-webserver" "*.stellar-dev-webserver"

  # Nginx Webserver and proxy
  webserver:
    image: nginx:alpine
    container_name: stellar-dev-webserver
    environment:
      WORDPRESS_REMOTE_URL: ${WORDPRESS_REMOTE_URL:-https://stellarwp.com}
      WORDPRESS_CONTAINER: stellar-dev-wp
    volumes:
      - ./docker/webserver/nginx-templates:/etc/nginx/templates:ro
      - wp-data:/var/www/html
      - cert-data:/root/.local/share/mkcert
    command:
      - sh
      - -c
      - |
        envsubst '$$WORDPRESS_CONTAINER,$$WORDPRESS_REMOTE_URL' < /etc/nginx/templates/wordpress.conf > /etc/nginx/conf.d/wordpress.conf
        rm -f /etc/nginx/conf.d/default.conf
        nginx -g 'daemon off;'
    ports:
      - ${WORDPRESS_PORT_HTTP:-8000}:80
      - ${WORDPRESS_PORT_HTTPS:-8001}:443
    depends_on:
      - mkcert

  # WordPress Application
  wp:
    build:
      context: ./docker/wp/
      args:
        - WORDPRESS_VERSION=${WORDPRESS_VERSION:-fpm}
    container_name: stellar-dev-wp
    environment:
      WORDPRESS_DB_HOST: stellar-dev-db
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'WP_DEBUG_LOG', '/tmp/wordpress/wordpress.log' );
        define( 'WP_REDIS_HOST', 'stellar-dev-cache' );
    volumes:
      # configuration files
      - ./docker/wp/msmtprc:/etc/msmtprc
      - ./docker/wp/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./docker/wp/msmtp-mailhost-fixer.php:/var/www/html/wp-content/mu-plugins/msmtp-mailhost-fixer.php
      # Enable log access
      - ./logs/xdebug:/tmp/xdebug
      - ./logs/wordpress:/tmp/wordpress
      # WordPress files
      - wp-data:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins

  # MariaDB database
  db:
    image: mariadb
    container_name: stellar-dev-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    volumes:
      - db-data:/var/lib/mysql

networks:
  default:
    name: stellar-dev-network

volumes:
  db-data:
  wp-data:
  cert-data:

# vim: wrap
