version: "3"

services:

  # Nginx Webserver and proxy
  http:
    image: nginx:alpine
    container_name: stellar-dev-webserver
    environment:
      WORDPRESS_REMOTE_URL: ${WORDPRESS_REMOTE_URL:-https://remote-site-media}
    volumes:
      - ./docker/http/nginx-templates:/etc/nginx/templates:ro
      - ./:/var/www/html
    command:
      - sh
      - -c
      - |
        envsubst '$$WORDPRESS_CONTAINER,$$WORDPRESS_REMOTE_URL' < /etc/nginx/templates/wordpress.conf > /etc/nginx/conf.d/wordpress.conf
        rm -f /etc/nginx/conf.d/default.conf
        nginx -g 'daemon off;'
    ports:
      - 8000:80


networks:
  default:
    name: learndash-wp-proxy-network

volumes:
  db-data:
  wp-data:
  cert-data:

# vim: wrap
