version: "3"

services:
  # MariaDB database
  db:
    image: mariadb
    container_name: stellar-dev-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql

  # Redis cache
  cache:
    image: redis:alpine
    container_name: stellar-dev-cache

  # MailHog mail catcher
  mail:
    image: mailhog/mailhog
    container_name: stellar-dev-mail
    ports:
      - ${MAIL_PORT:-8001}:8025

  # WordPress Application
  wp:
    build:
      context: ./docker/wp/
      args:
        - WORDPRESS_VERSION=${WORDPRESS_VERSION:-6}
    container_name: stellar-dev-wp
    environment:
      WORDPRESS_DB_HOST: stellar-dev-db
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'WP_DEBUG_LOG', '/tmp/wordpress/wordpress.log' );
        define( 'WP_REDIS_HOST', 'stellar-dev-cache' );
    volumes:
      # configuration files
      - ./docker/wp/msmtprc:/etc/msmtprc
      - ./docker/wp/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./docker/wp/msmtp-mailhost-fixer.php:/var/www/html/wp-content/mu-plugins/msmtp-mailhost-fixer.php
      # Enable log access
      - ./logs/xdebug:/tmp/xdebug
      - ./logs/wordpress:/tmp/wordpress
      # WordPress files
      - wp-data:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins

  # PhpMyAdmin
  pma:
    image: phpmyadmin
    container_name: stellar-dev-pma
    environment:
      PMA___HOST: stellar-dev-db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-wordpress}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
    ports:
      - ${PMA_PORT:-8002}:80

  # Generate SSL certs for the local development environment.
  mkcert:
    build: ./docker/mkcert
    container_name: stellar-dev-mkcert
    volumes:
      - cert-data:/root/.local/share/mkcert
    command: mkcert -cert-file "${WORDPRESS_HOST:-stellar.local}.crt" -key-file "${WORDPRESS_HOST:-stellar.local}.key" "${WORDPRESS_HOST:-stellar.local}" "*.${DEV_URL:-stellar.local}"

  # Nginx proxy to support SSL Certificates ane remote media redirect
  proxy:
    image: nginx:alpine
    container_name: stellar-dev-proxy
    environment:
      WORDPRESS_HOST: stellar-dev-wp
      WORDPRESS_PROD_URL: ${WORDPRESS_PROD_URL:-https://remote-site-media}
    volumes_from:
      - mkcert
    volumes:
      - ./docker/proxy/nginx-templates:/etc/nginx/templates:ro
    ports:
      - ${WORDPRESS_PORT:-8000}:80
    command:
      - sh
      - -c
      - |
        envsubst '$$WORDPRESS_HOST,$$WORDPRESS_PROD_URL' < /etc/nginx/templates/wordpress.conf > /etc/nginx/conf.d/wordpress.conf
        rm -f /etc/nginx/conf.d/default.conf
        nginx -g 'daemon off;'

  # WordPress installation
  wp-cli:
    image: wordpress:cli
    container_name: stellar-dev-cli
    environment:
      WORDPRESS_HOST: ${WORDPRESS_HOST:-localhost} # To pass to wp-cli
      WORDPRESS_PORT: ${WORDPRESS_PORT:-8000}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER:-admin}
      WORDPRESS_ADMIN_PASS: ${WORDPRESS_ADMIN_PASS:-password}
      WORDPRESS_DB_HOST: stellar-dev-db
      WORDPRESS_DB_USER: ${MYSQL_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-wordpress}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEGUB_DISPLAY', false );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_REDIS_HOST', 'stellar-dev-cache' );
    volumes_from:
      - wp
    user: xfs
    command:
      - sh
      - -c
      - |
        sleep 10
        wp core install --path=/var/www/html --title=LD_DEV --admin_user=$${WORDPRESS_ADMIN_USER} --admin_password=$${WORDPRESS_ADMIN_PASS} --admin_email=admin@example.com --skip-email --url="http://$${WORDPRESS_HOST}:$${WORDPRESS_PORT}"
        wp plugin install redis-cache --activate
        wp redis enable
        echo "Go to http://$${WORDPRESS_HOST}:$${WORDPRESS_PORT}/wp-admin/ with User $${WORDPRESS_ADMIN_USER} and password $${WORDPRESS_ADMIN_PASS}"

networks:
  default:
    name: learndash-wp-proxy-network

volumes:
  db-data:
  wp-data:
  cert-data:
